version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongo-data:/data/db
    environment:
      node.name: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

  mongo-express:
    build:
      context: mongo-express/
    restart: always
    ports:
      - 8081:8081
    environment:
      node.name: mongo-express
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017/
